name: envy-merge

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]
    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu    # Linux
          - x86_64-apple-darwin         # macOS Intel (Local Runner)
          - aarch64-apple-darwin        # macOS Apple Silicon (Local Runner)
          - x86_64-pc-windows-gnu       # Windows (Local Runner)

        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: aarch64-apple-darwin
            os: self-hosted-macos

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Install Dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y clang llvm cmake

    - name: Build
      run: cargo build --release --target=${{ matrix.target }}

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: envy-merge-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/envy-merge*