name: envy-merge

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt

    - name: Install Rust target for macOS
      run: rustup target add aarch64-apple-darwin

    - name: Install dependencies (Linux)
      run: sudo apt update && sudo apt install -y clang cmake llvm

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: brew install cmake llvm

    - name: Ensure Cargo.lock exists
      run: cargo generate-lockfile || true

    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: rust-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          rust-cache-${{ runner.os }}-

    - name: Fetch dependencies
      run: cargo fetch

  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        components: clippy, rustfmt

    - name: Run Clippy (Linting)
      run: cargo clippy --target=${{ matrix.target }} -- -D warnings

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --release --target=${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose --target=${{ matrix.target }}

    - name: Fix macOS binary permissions
      if: matrix.target == 'aarch64-apple-darwin'
      run: chmod +x target/${{ matrix.target }}/release/envy-merge

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: envy-merge-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/envy-merge*

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download built binaries
      uses: actions/download-artifact@v4
      with:
        path: binaries

    - name: Fix macOS binary permissions before release
      run: chmod +x binaries/envy-merge-aarch64-apple-darwin || true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: binaries/**
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}